version: 2.1

executors:
  demo-executor:
    docker:
      - image: cimg/php:8.0.10
        environment:
          DB_CONNECTION: circle_testing
      - image: circleci/mysql:8.0.26-ram
    working_directory: ~/src

jobs:
  setup:
    executor: demo-executor
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: |
            cd src &&
            composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./src/vender
          key: v1-dependencies-{{ checksum "src/composer.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - "src/vender"

  exec_test:
    executor: demo-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Run PHPUnit circle_testing
          command: |
            cd src &&
            php ./vendor/bin/phpunit

workflows:
  version: 2
  build_test:
    jobs:
      - setup
      - exec_test:
          requires:
            - setup
