version: 2
jobs:
  build:
    docker:
      - image: cimg/php:8.0.10
        environment:
          DB_CONNECTION: circle_testing
      - image: circleci/mysql:8.0.26-ram
    working_directory: ~/src
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: |
            cd src &&
            composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vender
          key: v1-dependencies-{{ checksum "src/composer.json" }}
      - run:
          name: CI Output Test
          command: |
            echo "CI is $CI"
            echo "CIRCLE_BRANCH is $CIRCLE_BRANCH"
            echo "CIRCLE_PROJECT_REPONAME is $CIRCLE_PROJECT_REPONAME"
      - run:
          name: Run PHPUnit circle_testing
          command: |
            cd src &&
            php ./vendor/bin/phpunit
