version: 2
jobs:
  build:
    docker:
      - image: cimg/php:8.0.10
        environment:
          DB_CONNECTION: circle_testing
      - image: circleci/mysql:8.0.26-ram
    steps:
      - run: checkout
      - run: php --version
